name: k8s-golang
version: v5
codeRepo: https://github.com/fhquthpdw/k8s-golang.git
dockerImageRepoCI: registry.iherb.local.zdc
dockerImageRepoCD: registry-svc.daochun.svc.cluster.local
tasks:
- name: prebuild
  command:
  - echo "prebuild ..."
- name: build
  command:
  - echo "build ..."
